# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8111531df6394fc8d266ccafd4c7080e2699e77990a4381fb9997d0bbfbc2651ae2cce36a90d051e2479fe5b13fcf5d83ba4818dc270318a042557c3747b23c

test:
  secret_key_base: a79afa58b51a870fc86475439027aebd5617756ff3621f6abbfee35882e90fac48ab0dd13e30d5340abc126a5630465b177bf8032a5a14c3c347e9e8b8544a92

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
